version: "3"
services:
  nest-app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - "${APP_PORT}:3000"
    environment:
      - DB_URL=${MONGO_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

volumes:
  mongodata: 